apiVersion: v1
kind: Service
metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{ if eq .Values.service.type "NodePort" }}
      nodePort: 30001 
      {{ end }}
  selector:
    {{- include "backend.selectorLabels" . | nindent 4 }}
