"""Added blog table

Revision ID: 575643bc8cbc
Revises: da9301b43279
Create Date: 2022-06-01 10:53:40.631185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '575643bc8cbc'
down_revision = 'da9301b43279'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('body', sa.Text, nullable=False),
    sa.Column('submitter_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['submitter_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blog_body'), 'blog', ['body'], unique=False)
    op.create_index(op.f('ix_blog_id'), 'blog', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blog_id'), table_name='blog')
    op.drop_index(op.f('ix_blog_body'), table_name='blog')
    op.drop_table('blog')
    # ### end Alembic commands ###
